global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'ingestor'
    static_configs:
      - targets: ['ingestor:3000']
  - job_name: 'entity-extractor'
    static_configs:
      - targets: ['entity-extractor:3000']
