{
 "title": "The Entity Extractor",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Message Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(entity_extractor_message_duration_seconds_sum[1m])\n/\nrate(entity_extractor_message_duration_seconds_count[1m])\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, rate(entity_extractor_message_duration_seconds_bucket[1m]))\n",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.50, rate(entity_extractor_message_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, rate(entity_extractor_message_duration_seconds_bucket[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM requests / minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(entity_extractor_messages_consumed_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Rate (%)",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(entity_extractor_llm_failures_total[1m]) / rate(entity_extractor_llm_requests_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entities Per Content",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(entity_extractor_entities_extracted_total[1m]) / rate(entity_extractor_messages_consumed_total[1m])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LLM Extractions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "entity_extractor_llm_requests_total\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}